const List quesans = [
  //1

  [
    {
      'question': 'Note: Please click on green answer button to view answer ',
      'option a': ' Oh sure ',
      'option b': ' Okay',
      'option c': ' Both ',
      'option d': '  None ',
      'answer': ' will be improved in next update ',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question':
          'Two bulbs 60w, 200v and 100w at 110v are connected to a voltage source of 400v. The ratio of resistance of two bulbs is ',
      'option a': ' 5:3',
      'option b': '10:3 ',
      'option c': '15:3 ',
      'option d': '20:3 ',
      'answer': ' 20:3',
      'solution': 'https://www.neptechpal.com ',
    },
//3
    {
      'question':
          'A proton moving in a straight line enters a strong magnetic field along the field direction. Its path is ',
      'option a': ' Circular',
      'option b': ' Elliptical',
      'option c': ' Straight ',
      'option d': ' Hyperbolic',
      'answer': ' Straight',
      'solution': 'https://www.neptechpal.com ',
    },
//4
    {
      'question':
          'A coil of resistance 2Ω and inductance 4H is connected to a battery of emf E volts. The final steady current in the coil is ',
      'option a': ' E/√20 Amp',
      'option b': ' E/2 Amp',
      'option c': '  E/4 Amp',
      'option d': '2E Amp ',
      'answer': ' E/2 Amp',
      'solution': 'https://www.neptechpal.com ',
    },
//5
    {
      'question':
          'A charge ‘q’ is placed at center of cube, the net flux through one wall is ',
      'option a': ' 0',
      'option b': ' a/E0',
      'option c': 'a/5E0 ',
      'option d': ' a/6E0',
      'answer': 'a/6E0',
      'solution': 'https://www.neptechpal.com ',
    },
//7
    {
      'question':
          'A mass is placed at the top of hemisphere path of radius 60m. The mass just starts to slip. Find the height from the bone of path where the mass leaves positive path ',
      'option a': '  20m',
      'option b': '  40m',
      'option c': ' 45m ',
      'option d': '  60m',
      'answer': '40 m ',
      'solution': 'https://www.neptechpal.com ',
    },
//8
    {
      'question':
          'A vessel of depth 2d cm is filled with two different liquid upper half with 𝜇1 and lower half with 𝜇2. The apparent depth of the vessel seen perpendicularly is ',
      'option a': '( 𝜇1+𝜇2/ 𝜇1𝜇2)d/2  ',
      'option b': ' (1/ μ 1+ 1/ μ 2)d',
      'option c': 'both  ',
      'option d': ' none',
      'answer': '(1/ μ 1+ 1/ μ 2)d ',
      'solution': 'https://www.neptechpal.com ',
    },
//9
    {
      'question':
          'A convex lens of focal length 20cm and other convex lens of focal length 10cm are separated by a distance 5cm for working of this combination the equivalent focal length is ',
      'option a': ' 5 cm',
      'option b': ' 6 cm',
      'option c': ' 7 cm',
      'option d': ' 8 cm',
      'answer': ' 8 cm',
      'solution': 'https://www.neptechpal.com ',
    },
//10
    {
      'question':
          'If 8 drops of mercury each having potential v combines to from a bigger drop then ratio of potential of drop formed to initial drop is',
      'option a': '  2:3',
      'option b': '  4:1',
      'option c': '  1:3',
      'option d': ' 2:5 ',
      'answer': '  4:1',
      'solution': 'https://www.neptechpal.com ',
    },
//11
    {
      'question':
          'The flux (in weber) in a closed circuit of a resistance 10 Ω varies with time t (in seconds) as 𝜙 = 6t25t+1. The magnitude of induced currents at t = 0.25sec is ',
      'option a': '1.2 A ',
      'option b': ' 2.1 A',
      'option c': ' 2.0 A',
      'option d': '  0.2A ',
      'answer': '  0.2 A ',
      'solution': 'https://www.neptechpal.com ',
    },
//12
    {
      'question':
          'What must be duration of one day of weightlessness at equator? a',
      'option a': '1.4hrs  ',
      'option b': ' 1.9hrs ',
      'option c': '2.4hrs  ',
      'option d': '1.6hrs  ',
      'answer': ' 1.4hrs ',
      'solution': 'https://www.neptechpal.com ',
    },
//13
    {
      'question':
          'Two identical rods of same material, one placed end to end between steam chamber and ice chamber then 2gm of ice melts in 1 min. It they are placed side by side then find mass of ice melts in 2 min. ',
      'option a': ' 2 gm ',
      'option b': ' 4 gm ',
      'option c': ' 6 gm',
      'option d': ' 8 gm',
      'answer': ' 4 gm ',
      'solution': 'https://www.neptechpal.com ',
    },
//14
    {
      'question':
          'If the number of degrees of freedom of a gas is f, then the value of γ will be ',
      'option a': ' f',
      'option b': ' 2f ',
      'option c': '1+f/2 ',
      'option d': ' 1+2/f',
      'answer': ' 1+2/f',
      'solution': 'https://www.neptechpal.com ',
    },
//15
    {
      'question':
          'Lengths of elastic wire is ‘a’ when 4N force acts and ‘b’ when 5N force acts. Find length when 9N force acts. ',
      'option a': ' 5a+5b',
      'option b': '5b+4a ',
      'option c': ' 5b- 4a',
      'option d': ' 4b-5a',
      'answer': ' 5b- 4a',
      'solution': 'https://www.neptechpal.com ',
    },
//16
    {
      'question':
          ' A base player can throw a ball a maximum distance ‘d’ over the ground. The maximum vertical height to which he can throw is ',
      'option a': ' d',
      'option b': '2d ',
      'option c': 'd/2 ',
      'option d': ' d/4',
      'answer': 'd/4 ',
      'solution': 'https://www.neptechpal.com ',
    },
//17
    {
      'question': 'The color of light thin film due to ',
      'option a': 'Interface of light  ',
      'option b': ' dispersion of light',
      'option c': 'scattering of light  ',
      'option d': ' selective absorption of light ',
      'answer': 'Interface of light ',
      'solution': 'https://www.neptechpal.com ',
    },
//18
    {
      'question':
          'The maximum wave length of photo electrons from metal is 4000A. The work function of metal is ',
      'option a': ' 4eV ',
      'option b': '  3.1eV',
      'option c': ' 3.125eV ',
      'option d': ' 21.2 ev',
      'answer': ' 3.1eV ',
      'solution': 'https://www.neptechpal.com ',
    },
//19
    {
      'question': 'The speed of sound v is related to pressure is ',
      'option a': 'V proportional to  root P ',
      'option b': 'V proportional to P square ',
      'option c': 'V proportional to P ',
      'option d': ' V is independent of P ',
      'answer': 'V is independent of P  ',
      'solution': 'https://www.neptechpal.com ',
    },
//20
    {
      'question':
          'N equal capacitor are first connected in series and then in parallel. The ratio of maximum and minimum capacitance is',
      'option a': 'n power 2 : 1 ',
      'option b': '1 : n ',
      'option c': 'n',
      'option d': ' d/ root n',
      'answer': ' n power 2 : 1 ',
      'solution': 'https://www.neptechpal.com ',
    },
//21
    {
      'question':
          'The impurity atom which of should be dripped in pure silicon to make p-type semiconductor is ',
      'option a': ' Phosphorous  ',
      'option b': '  antimony ',
      'option c': ' boron',
      'option d': 'palladium ',
      'answer': 'boron ',
      'solution': 'https://www.neptechpal.com ',
    },
  ],

//2

  [
    {
      'question':
          'The coefficient of cubical expansion of brass and iron are 54 × 10−6     0 C−1 and 36 × 10−6     0 C−1. If brass and iron rods shows the same difference of length of all temperature, their lengths are in the ratio of  ',
      'option a': '  3:2 ',
      'option b': ' 2:3  ',
      'option c': '9:4  ',
      'option d': '4:9 ',
      'answer': ' 2:3',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question':
          'The temperature at which water vapour in the atmosphere is saturated ',
      'option a': 'Critical temperature  ',
      'option b': ' Dew point  ',
      'option c': 'Both ',
      'option d': 'none ',
      'answer': ' Dew point  ',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question':
          'The Crms of a gas is  γ0(not), When initial pressure P0 is doubled at constant tempr  To , then new Crms is ',
      'option a': ' Vo ',
      'option b': ' 2Vo',
      'option c': ' vo/2',
      'option d': 'none ',
      'answer': ' Vo',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question':
          'In refrigerator 3J of heat is delivered to the surrounding for every joule of work done. The coefficient of performance is ',
      'option a': '1 ',
      'option b': '2 ',
      'option c': '3 ',
      'option d': '4 ',
      'answer': '2 ',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question':
          'Sound waves are travelling in medium whose adiabatic elasticity is E, and isothermal elasticity is E1 and isothermal electricity is E2.The velocity of sound proportional to  a',
      'option a': ' E1',
      'option b': ' E2',
      'option c': ' root E1',
      'option d': ' none',
      'answer': 'root E1 ',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question': 'A change in temperature affects which property of sound',
      'option a': ' frequency  ',
      'option b': ' amplitude ',
      'option c': ' Wavelength',
      'option d': ' loudness ',
      'answer': 'Wavelength ',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question':
          'A tube closed at one end has a resonating length 1m. The air column in the πpe can resonate for sound of frequency',
      'option a': '80Hz  ',
      'option b': ' 166Hz',
      'option c': ' 249Hz  ',
      'option d': ' 575Hz ',
      'answer': ' 80Hz ',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question':
          'Two plane mirrors are inclined at a certain angle undergoes a deviation of 3000 .The no of image observed is ',
      'option a': '8 ',
      'option b': '9 ',
      'option c': ' 11',
      'option d': '12 ',
      'answer': '11 ',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question': 'Optical fiber is based on phenomena ',
      'option a': ' total internal reflection',
      'option b': 'Interference ',
      'option c': ' Diffraction',
      'option d': 'Polarization ',
      'answer': 'total internal reflection ',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question':
          'In a right – angled glass prism , light is normally incident on smaller face, then deviation is ',
      'option a': '90 deg ',
      'option b': '45 deg ',
      'option c': '30 deg ',
      'option d': '60 deg ',
      'answer': '90 deg ',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question':
          'A person cannot see object clearly beyond 50cm. The power of lens to correct the vision is  a',
      'option a': ' -0.5D',
      'option b': ' 6D',
      'option c': ' -5D',
      'option d': ' -2D',
      'answer': ' -2D',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question':
          'A 10 kg mass is held 1 m above the table for 25 sec. calculate the work done ',
      'option a': ' 9.8 J',
      'option b': ' 10 J',
      'option c': ' 250J',
      'option d': ' none',
      'answer': ' none',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question': 'At what height from surface of earth g becomes /2 ? ',
      'option a': ' R/ 2',
      'option b': '0.414 R ',
      'option c': ' R',
      'option d': ' 0.7R',
      'answer': '0.414R ',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question':
          'Two charges -10 c and +10c are placed 10 cm  part .The potential at midpoint between their center’s is ',
      'option a': ' 0 V',
      'option b': '2 V ',
      'option c': ' -2V',
      'option d': 'none ',
      'answer': '0 V ',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question':
          'A bulb rated 220V, 100W is connected across 160V line. The power dissipated will be ',
      'option a': '100 W ',
      'option b': ' 75 W',
      'option c': '52W ',
      'option d': ' 26W',
      'answer': '52 W ',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question':
          'A battery is corrected in a thermocouple. The 2 junctions will',
      'option a': 'be heated up ',
      'option b': '  remain at same temperature ',
      'option c': 'be cooled  ',
      'option d': '  be heated at one junction and cooled at other',
      'answer': ' be heated at one junction and cooled at other ',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question': 'Which one is paramagnetic substance',
      'option a': 'Na ',
      'option b': 'Cu ',
      'option c': 'Pd ',
      'option d': 'none ',
      'answer': ' Na',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question': 'Compton effect  related to ',
      'option a': ' Photoelectric effect',
      'option b': 'polarization  ',
      'option c': ' Diffraction',
      'option d': ' Interference ',
      'answer': ' Photo Electric Effect',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question': 'The internal structure of crystal can be studied by',
      'option a': 'X rays ',
      'option b': 'Gama Rays ',
      'option c': 'UV rays ',
      'option d': ' none',
      'answer': 'X rays ',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question':
          'P-fund series is obtained when electrons jump from higher orbit to',
      'option a': '5 ',
      'option b': '4 ',
      'option c': ' 6',
      'option d': ' none',
      'answer': '5 ',
      'solution': 'https://www.neptechpal.com ',
    },
  ],

  //3

  [
    {
      'question': 'The number of moles present in 90g of water is',
      'option a': '5.0 ',
      'option b': '90.0 ',
      'option c': ' 9.0',
      'option d': ' 10',
      'answer': '90.0 ',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question':
          '1g of Hcl reacts with 1g of CaCO3 , the volume of CO2 produced at NTP would be equal to ',
      'option a': '4.22 ',
      'option b': '22.4 ',
      'option c': ' 2.24 liter ',
      'option d': ' 22.24 liter ',
      'answer': ' 2.24 liter ',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question':
          'Atomic orbitals are filled up in the ground state in order of increasing energy level. This statement is ',
      'option a': 'Hund’s rule  ',
      'option b': 'Pauli’s exclusion principle ',
      'option c': ' Aufbau principle',
      'option d': 'Heisenberg’s uncertainty principle  ',
      'answer': 'Hunds rule ',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question':
          'The spectral region for the Lyman series  of hydrogen spectrum lies in the ',
      'option a': '  ultra-violet region ',
      'option b': ' microwave region',
      'option c': 'visible region ',
      'option d': 'Infrared region ',
      'answer': '  ultra-violet region ',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question': 'The oxidation number of Fe in the compound Fe3O4 is',
      'option a': ' 2',
      'option b': '+ 6/3 ',
      'option c': '+ 8/3 ',
      'option d': ' + 4/3',
      'answer': '2 ',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question':
          'Which of the following metals generate H20 on treatment with dill. HNO3 ',
      'option a': ' Zn',
      'option b': ' Mn',
      'option c': ' Cu',
      'option d': ' Pb',
      'answer': ' Zn',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question':
          'In which of the following compound the molecular geometry cannot be predicted by the use of USE/oR theory? ',
      'option a': 'Nacl ',
      'option b': ' h2o',
      'option c': ' ch4',
      'option d': ' NH3',
      'answer': 'Nacl ',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question': 'The rate of reaction is independent of ',
      'option a': ' Temperatur',
      'option b': 'Particle size of reactant ',
      'option c': ' Concentration  ',
      'option d': 'molecularit ',
      'answer': ' molecularit',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question': 'The CGS unit of specific conductance is ',
      'option a': ' Siemencm-1 ',
      'option b': ' ohm',
      'option c': 'Siemen  ',
      'option d': ' ohm-1cm2equiv-1 ',
      'answer': ' Siemencm power -1 ',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question': 'The equivalent weight of KMno4 in neutral medium is',
      'option a': '52.6 g ',
      'option b': ' 158.0g ',
      'option c': '31.6 g  ',
      'option d': '63.0g ',
      'answer': ' 52.6 g',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question':
          'If the pH of solution is 5.2, the hydrogen ion concentration of the solution is ',
      'option a': '6.3 X 10-6m ',
      'option b': '6.3 X 10-9m ',
      'option c': ' 6.3 X 10-4m',
      'option d': '6.3 X 10-7m ',
      'answer': ' 6.3 X 10-6m',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question': 'The oxidation state of iron in Mohr’s salt is ',
      'option a': ' +2',
      'option b': ' +3',
      'option c': '+1 ',
      'option d': ' none',
      'answer': ' +2',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question': 'Which of the following oxides is acidic',
      'option a': ' No2',
      'option b': ' CO2',
      'option c': ' Co',
      'option d': 'Feo ',
      'answer': ' CO2',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question':
          'Which of the following elements has highest electro-negativity ',
      'option a': '  Fluorine ',
      'option b': ' Chlorine',
      'option c': 'Bromine ',
      'option d': ' Iodine',
      'answer': '  Fluorine ',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question': 'ZnSO4 .7H20 is also called ',
      'option a': 'White Vitroil ',
      'option b': ' Green Vitroil',
      'option c': 'Blue vitroil ',
      'option d': ' none',
      'answer': 'White Vitroil ',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question': '',
      'option a': 'Copper and zinc ',
      'option b': 'Copper and tin ',
      'option c': 'Copper and nickel  ',
      'option d': ' none',
      'answer': ' Copper and zinc',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question': 'The general electronic configuration of Zn is ',
      'option a': ' [Ar]4s23d10',
      'option b': ' [Ar] 4s23d8 ',
      'option c': ' [Ar] 4s23d7 ',
      'option d': ' none',
      'answer': ' [Ar]4s23d10',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question': 'The formula of dolomite is ',
      'option a': 'CaCO3.MgCO3 ',
      'option b': ' CaF12  ',
      'option c': ' CaSO4 2H2O ',
      'option d': ' none',
      'answer': 'CaCO3.MgCO3 ',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question':
          'Electronic Configuration of four elements A, B, C, D are as follow, which will be most metallic? ',
      'option a': 'A = 2,8,4  ',
      'option b': ' B = 2,8,8',
      'option c': '  D = 2,8,7 ',
      'option d': ' C = 2,8,1',
      'answer': ' C = 2,8,1',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question': 'Ammonia is manufactured by use of ',
      'option a': ' Ostwalds process',
      'option b': 'Solvay Process ',
      'option c': '  Haber’s process',
      'option d': ' Downs process',
      'answer': ' Haber’s process ',
      'solution': 'https://www.neptechpal.com ',
    },
  ],

  //4

  [
    {
      'question': 'New Questions will be added soon please check for updates. ',
      'option a': 'Okay ',
      'option b': 'Send us email',
      'option c': 'For more',
      'option d': ' Question we have pdfs',
      'answer': '90.0 ',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question':
          '1g of Hcl reacts with 1g of CaCO3 , the volume of CO2 produced at NTP would be equal to ',
      'option a': '4.22 ',
      'option b': '22.4 ',
      'option c': ' 2.24 liter ',
      'option d': ' 22.24 liter ',
      'answer': ' 2.24 liter ',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question':
          'Atomic orbitals are filled up in the ground state in order of increasing energy level. This statement is ',
      'option a': 'Hund’s rule  ',
      'option b': 'Pauli’s exclusion principle ',
      'option c': ' Aufbau principle',
      'option d': 'Heisenberg’s uncertainty principle  ',
      'answer': 'Hunds rule ',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question':
          'The spectral region for the Lyman series  of hydrogen spectrum lies in the ',
      'option a': '  ultra-violet region ',
      'option b': ' microwave region',
      'option c': 'visible region ',
      'option d': 'Infrared region ',
      'answer': '  ultra-violet region ',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question': 'The oxidation number of Fe in the compound Fe3O4 is',
      'option a': ' 2',
      'option b': '+ 6/3 ',
      'option c': '+ 8/3 ',
      'option d': ' + 4/3',
      'answer': '2 ',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question':
          'Which of the following metals generate H20 on treatment with dill. HNO3 ',
      'option a': ' Zn',
      'option b': ' Mn',
      'option c': ' Cu',
      'option d': ' Pb',
      'answer': ' Zn',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question':
          'In which of the following compound the molecular geometry cannot be predicted by the use of USE/oR theory? ',
      'option a': 'Nacl ',
      'option b': ' h2o',
      'option c': ' ch4',
      'option d': ' NH3',
      'answer': 'Nacl ',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question': 'The rate of reaction is independent of ',
      'option a': ' Temperatur',
      'option b': 'Particle size of reactant ',
      'option c': ' Concentration  ',
      'option d': 'molecularit ',
      'answer': ' molecularit',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question': 'The CGS unit of specific conductance is ',
      'option a': ' Siemencm-1 ',
      'option b': ' ohm',
      'option c': 'Siemen  ',
      'option d': ' ohm-1cm2equiv-1 ',
      'answer': ' Siemencm power -1 ',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question': 'The equivalent weight of KMno4 in neutral medium is',
      'option a': '52.6 g ',
      'option b': ' 158.0g ',
      'option c': '31.6 g  ',
      'option d': '63.0g ',
      'answer': ' 52.6 g',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question':
          'If the pH of solution is 5.2, the hydrogen ion concentration of the solution is ',
      'option a': '6.3 X 10-6m ',
      'option b': '6.3 X 10-9m ',
      'option c': ' 6.3 X 10-4m',
      'option d': '6.3 X 10-7m ',
      'answer': ' 6.3 X 10-6m',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question': 'The oxidation state of iron in Mohr’s salt is ',
      'option a': ' +2',
      'option b': ' +3',
      'option c': '+1 ',
      'option d': ' none',
      'answer': ' +2',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question': 'Which of the following oxides is acidic',
      'option a': ' No2',
      'option b': ' CO2',
      'option c': ' Co',
      'option d': 'Feo ',
      'answer': ' CO2',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question':
          'Which of the following elements has highest electro-negativity ',
      'option a': '  Fluorine ',
      'option b': ' Chlorine',
      'option c': 'Bromine ',
      'option d': ' Iodine',
      'answer': '  Fluorine ',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question': 'ZnSO4 .7H20 is also called ',
      'option a': 'White Vitroil ',
      'option b': ' Green Vitroil',
      'option c': 'Blue vitroil ',
      'option d': ' none',
      'answer': 'White Vitroil ',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question': '',
      'option a': 'Copper and zinc ',
      'option b': 'Copper and tin ',
      'option c': 'Copper and nickel  ',
      'option d': ' none',
      'answer': ' Copper and zinc',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question': 'The general electronic configuration of Zn is ',
      'option a': ' [Ar]4s23d10',
      'option b': ' [Ar] 4s23d8 ',
      'option c': ' [Ar] 4s23d7 ',
      'option d': ' none',
      'answer': ' [Ar]4s23d10',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question': 'The formula of dolomite is ',
      'option a': 'CaCO3.MgCO3 ',
      'option b': ' CaF12  ',
      'option c': ' CaSO4 2H2O ',
      'option d': ' none',
      'answer': 'CaCO3.MgCO3 ',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question':
          'Electronic Configuration of four elements A, B, C, D are as follow, which will be most metallic? ',
      'option a': 'A = 2,8,4  ',
      'option b': ' B = 2,8,8',
      'option c': '  D = 2,8,7 ',
      'option d': ' C = 2,8,1',
      'answer': ' C = 2,8,1',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question': 'Ammonia is manufactured by use of ',
      'option a': ' Ostwalds process',
      'option b': 'Solvay Process ',
      'option c': '  Haber’s process',
      'option d': ' Downs process',
      'answer': ' Haber’s process ',
      'solution': 'https://www.neptechpal.com ',
    },
  ],

  //5

  [
    {
      'question': 'The number of moles present in 90g of water is',
      'option a': '5.0 ',
      'option b': '90.0 ',
      'option c': ' 9.0',
      'option d': ' 10',
      'answer': '90.0 ',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question':
          '1g of Hcl reacts with 1g of CaCO3 , the volume of CO2 produced at NTP would be equal to ',
      'option a': '4.22 ',
      'option b': '22.4 ',
      'option c': ' 2.24 liter ',
      'option d': ' 22.24 liter ',
      'answer': ' 2.24 liter ',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question':
          'Atomic orbitals are filled up in the ground state in order of increasing energy level. This statement is ',
      'option a': 'Hund’s rule  ',
      'option b': 'Pauli’s exclusion principle ',
      'option c': ' Aufbau principle',
      'option d': 'Heisenberg’s uncertainty principle  ',
      'answer': 'Hunds rule ',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question':
          'The spectral region for the Lyman series  of hydrogen spectrum lies in the ',
      'option a': '  ultra-violet region ',
      'option b': ' microwave region',
      'option c': 'visible region ',
      'option d': 'Infrared region ',
      'answer': '  ultra-violet region ',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question': 'The oxidation number of Fe in the compound Fe3O4 is',
      'option a': ' 2',
      'option b': '+ 6/3 ',
      'option c': '+ 8/3 ',
      'option d': ' + 4/3',
      'answer': '2 ',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question':
          'Which of the following metals generate H20 on treatment with dill. HNO3 ',
      'option a': ' Zn',
      'option b': ' Mn',
      'option c': ' Cu',
      'option d': ' Pb',
      'answer': ' Zn',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question':
          'In which of the following compound the molecular geometry cannot be predicted by the use of USE/oR theory? ',
      'option a': 'Nacl ',
      'option b': ' h2o',
      'option c': ' ch4',
      'option d': ' NH3',
      'answer': 'Nacl ',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question': 'The rate of reaction is independent of ',
      'option a': ' Temperature',
      'option b': 'Particle size of reactant ',
      'option c': ' Concentration  ',
      'option d': 'molecularit ',
      'answer': ' molecularit',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question': 'The CGS unit of specific conductance is ',
      'option a': ' Siemencm-1 ',
      'option b': ' ohm',
      'option c': 'Siemen  ',
      'option d': ' ohm-1cm2equiv-1 ',
      'answer': ' Siemencm power -1 ',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question': 'The equivalent weight of KMno4 in neutral medium is',
      'option a': '52.6 g ',
      'option b': ' 158.0g ',
      'option c': '31.6 g  ',
      'option d': '63.0g ',
      'answer': ' 52.6 g',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question':
          'If the pH of solution is 5.2, the hydrogen ion concentration of the solution is ',
      'option a': '6.3 X 10-6m ',
      'option b': '6.3 X 10-9m ',
      'option c': ' 6.3 X 10-4m',
      'option d': '6.3 X 10-7m ',
      'answer': ' 6.3 X 10-6m',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question': 'The oxidation state of iron in Mohr’s salt is ',
      'option a': ' +2',
      'option b': ' +3',
      'option c': '+1 ',
      'option d': ' none',
      'answer': ' +2',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question': 'Which of the following oxides is acidic',
      'option a': ' No2',
      'option b': ' CO2',
      'option c': ' Co',
      'option d': 'Feo ',
      'answer': ' CO2',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question':
          'Which of the following elements has highest electro-negativity ',
      'option a': '  Fluorine ',
      'option b': ' Chlorine',
      'option c': 'Bromine ',
      'option d': ' Iodine',
      'answer': '  Fluorine ',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question': 'ZnSO4 .7H20 is also called ',
      'option a': 'White Vitroil ',
      'option b': ' Green Vitroil',
      'option c': 'Blue vitroil ',
      'option d': ' none',
      'answer': 'White Vitroil ',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question': '',
      'option a': 'Copper and zinc ',
      'option b': 'Copper and tin ',
      'option c': 'Copper and nickel  ',
      'option d': ' none',
      'answer': ' Copper and zinc',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question': 'The general electronic configuration of Zn is ',
      'option a': ' [Ar]4s23d10',
      'option b': ' [Ar] 4s23d8 ',
      'option c': ' [Ar] 4s23d7 ',
      'option d': ' none',
      'answer': ' [Ar]4s23d10',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question': 'The formula of dolomite is ',
      'option a': 'CaCO3.MgCO3 ',
      'option b': ' CaF12  ',
      'option c': ' CaSO4 2H2O ',
      'option d': ' none',
      'answer': 'CaCO3.MgCO3 ',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question':
          'Electronic Configuration of four elements A, B, C, D are as follow, which will be most metallic? ',
      'option a': 'A = 2,8,4  ',
      'option b': ' B = 2,8,8',
      'option c': '  D = 2,8,7 ',
      'option d': ' C = 2,8,1',
      'answer': ' C = 2,8,1',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question': 'Ammonia is manufactured by use of ',
      'option a': ' Ostwalds process',
      'option b': 'Solvay Process ',
      'option c': '  Haber’s process',
      'option d': ' Downs process',
      'answer': ' Haber’s process ',
      'solution': 'https://www.neptechpal.com ',
    },
  ],

  //6

  [
    {
      'question': 'If A ∩ X = A ∩ Y and A ∪ X = A ∪ Y then, x = ',
      'option a': 'A ∩ X ',
      'option b': ' A ∩ Y ',
      'option c': ' Y ',
      'option d': 'Y ∩ X ',
      'answer': ' Y',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question': 'If f(x) = X /X−1= 1 /Y  , then f(y) ',
      'option a': 'x ',
      'option b': ' x+1',
      'option c': ' x-1',
      'option d': '1-x ',
      'answer': '1-x ',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question': 'If  loga √3  = 1/ 2,     then the value  loga a is',
      'option a': '0 ',
      'option b': '1 ',
      'option c': '3 ',
      'option d': '1 ',
      'answer': ' 3',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question': ' The domain of the function f(x)   = √|x| − x  is ',
      'option a': ' (0,∞',
      'option b': '0,1 ',
      'option c': '(0,-∞) ',
      'option d': ' (-∞,-∞)',
      'answer': '(-∞,-∞) ',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question': ' The domain of the function f(x)   = √|x| − x  is ',
      'option a': ' (0,∞',
      'option b': '0,1 ',
      'option c': '(0,-∞) ',
      'option d': ' (-∞,-∞)',
      'answer': '(-∞,-∞) ',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question':
          'If the difference of the roots of the equation  x2 + Kx + 7 = 0  is 6, then the possible values of k are   ',
      'option a': '4 ',
      'option b': ' -4',
      'option c': ' 8',
      'option d': ' +-8',
      'answer': ' +-8',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question': 'If R is the H.M between P & Q, then R /P+R/ Q = ',
      'option a': '   PQ /P+Q',
      'option b': '  P+Q /PQ ',
      'option c': '2 ',
      'option d': ' none',
      'answer': ' 2',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question':
          'If w is the cube root of unit, then the value of   (1 – w + w2) to power 5 + (1 + w - w2)to the power 5   = ',
      'option a': ' 16',
      'option b': '32 ',
      'option c': '48 ',
      'option d': '-16 ',
      'answer': ' 32',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question': 'The value of (i + i)20 is',
      'option a': ' 2 power 10',
      'option b': '2 power 15 ',
      'option c': ' 2 power 18 ',
      'option d': '2 power -10 ',
      'answer': ' 2 power -10',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question':
          'For what value of k the roots of the equation 3x2 − 2Kx + K = 0 are the ratio 3:1 ',
      'option a': ' 0 or 4  ',
      'option b': '0 or – 4  ',
      'option c': ' 1 or 3   ',
      'option d': ' none',
      'answer': '0 or 4   ',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question':
          ' tanθ + tan2θ + tanθtan2θ = 1 has general solution equations',
      'option a': 'π ',
      'option b': 'π/2 ',
      'option c': 'none ',
      'option d': '(4𝑛 + 1) 𝜋 /12 ',
      'answer': '(4𝑛 + 1) 𝜋 /12 ',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question':
          'The value of the h if the equation 4x2 + ℎxy + y2 = 0 represents the coincident lines is',
      'option a': ' ±5 ',
      'option b': ' ±4 ',
      'option c': ' ±2  ',
      'option d': '  ±3 ',
      'answer': ' ±4 ',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question':
          'The radius of the circle x2 + y2 − 2xcosθ + 2ysinθ − 8 = 0 is',
      'option a': '  8',
      'option b': '4 ',
      'option c': ' 9',
      'option d': '  3 ',
      'answer': ' 3  ',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question': 'The polar coordinates of ( 2,2√3) is ',
      'option a': ' none',
      'option b': 'both c and d ',
      'option c': '   ( 4,60 deg)  ',
      'option d': '   ( 2,30 deg) ',
      'answer': '   ( 4,60 deg) ',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question': ' Surprise Visit Our site at',
      'option a': 'www.neptechpal.com ',
      'option b': 'send us mail for pdf qna',
      'option c': 'Rate if app helps you ',
      'option d': 'Share if it deserves ',
      'answer': ' Sorry for stopping you',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question': 'The polar coordinates of ( 2,2√3) is ',
      'option a': ' none',
      'option b': 'both c and d ',
      'option c': '   ( 4,60 deg)  ',
      'option d': '   ( 2,30 deg) ',
      'answer': '   ( 4,60 deg) ',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question': 'The value of (i+ 1)20 is',
      'option a': ' 2 power 10',
      'option b': '2 power 15 ',
      'option c': ' 2 power 18 ',
      'option d': '2 power -10 ',
      'answer': ' options are incorrect, find answer yourself',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question': 'Every continuous function is ',
      'option a': ' Increasing     ',
      'option b': '  decreasing ',
      'option c': '  not always differentiable ',
      'option d': ' always differentiable ',
      'answer': ' not always differentiable  ',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question':
          'The general equation of 2nd degree 𝑎x2 + 2ℎxy + 𝑏y2 + 2𝑔x + 2𝑓y + 𝑐 = 0 represents a circle if',
      'option a': ' 𝑎 + 𝑏 = 0  ',
      'option b': '𝑎 = 𝑏 = ℎ = 0  ',
      'option c': ' 𝑎 = 𝑏;𝑐𝑜𝑒𝑓𝑓 𝑜𝑓 xy = 0  ',
      'option d': ' none',
      'answer': 'none ',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question':
          'If w is the cube root of unit, then the value of   (1 – w + w2) 5 + (1 + w - w2) 5   = ',
      'option a': ' 16',
      'option b': '32 ',
      'option c': '48 ',
      'option d': '-16 ',
      'answer': ' 32',
      'solution': 'https://www.neptechpal.com ',
    },
  ],

  //7

  [
    {
      'question': 'If A ∩ X = A ∩ Y and A ∪ X = A ∪ Y then, x = ',
      'option a': 'A ∩ X ',
      'option b': ' A ∩ Y ',
      'option c': ' Y ',
      'option d': 'Y intersection X ',
      'answer': ' Y',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question': 'If f(x) = X /X−1= 1 /Y  , then f(y) ',
      'option a': 'x ',
      'option b': ' x+1',
      'option c': ' x-1',
      'option d': '1-x ',
      'answer': '1-x ',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question': 'If  log𝑎 √3  = 1/ 2,     then the value  oa a is',
      'option a': '0 ',
      'option b': '1 ',
      'option c': '3 ',
      'option d': '1 ',
      'answer': ' 3',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question': ' The domain of the function f(x)   = √|x| − x  is ',
      'option a': ' (0,∞',
      'option b': '0,1 ',
      'option c': '(0,-∞) ',
      'option d': ' (-∞,-∞)',
      'answer': '(-∞,-∞) ',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question': ' The domain of the function f(x)   = √|x| − x  is ',
      'option a': ' (0,∞',
      'option b': '0,1 ',
      'option c': '(0,-∞) ',
      'option d': ' (-∞,-∞)',
      'answer': '(-∞,-∞) ',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question':
          'If the difference of the roots of the equation  x2 + Kx + 7 = 0  is 6, then the possible values of k are   ',
      'option a': '4 ',
      'option b': ' -4',
      'option c': ' 8',
      'option d': ' +-8',
      'answer': ' +-8',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question': 'If R is the H.M between P & Q, then R /P+R/ Q = ',
      'option a': '   PQ /P+Q',
      'option b': '  P+Q /PQ ',
      'option c': '2 ',
      'option d': ' none',
      'answer': ' 2',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question':
          'If w is the cube root of unit, then the value of   (1 – w + w2) 5 + (1 + w - w2) 5   = ',
      'option a': ' 16',
      'option b': '32 ',
      'option c': '48 ',
      'option d': '-16 ',
      'answer': ' 32',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question': 'The value of (𝑖 + 𝑖)20 is',
      'option a': ' 2 power 10',
      'option b': '2 power 15 ',
      'option c': ' 2 power 18 ',
      'option d': '2 power -10 ',
      'answer': ' 2 power -10',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question':
          'For what value of k the roots of the equation 3x2 − 2𝑘x + 𝑘 = 0 are the ratio 3:1 ',
      'option a': ' 0 or 4  ',
      'option b': '0 or – 4  ',
      'option c': ' 1 or 3   ',
      'option d': ' none',
      'answer': '0 or 4   ',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question':
          ' tanθ + tan2θ + tanθtan2θ = 1 has general solution equations',
      'option a': 'π ',
      'option b': 'π/2 ',
      'option c': 'none ',
      'option d': '(4𝑛 + 1) 𝜋 /12 ',
      'answer': '(4𝑛 + 1) 𝜋 /12 ',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question':
          'The value of the h if the equation 4x2 + ℎxy + y2 = 0 represents the coincident lines is',
      'option a': ' ±5 ',
      'option b': ' ±4 ',
      'option c': ' ±2  ',
      'option d': '  ±3 ',
      'answer': ' ±4 ',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question':
          'The radius of the circle x2 + y2 − 2xcosθ + 2ysinθ − 8 = 0 is',
      'option a': '  8',
      'option b': '4 ',
      'option c': ' 9',
      'option d': '  3 ',
      'answer': ' 3  ',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question': 'The polar coordinates of ( 2,2√3) is ',
      'option a': ' none',
      'option b': 'both c and d ',
      'option c': '   ( 4,60 deg)  ',
      'option d': '   ( 2,30 deg) ',
      'answer': '   ( 4,60 deg) ',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question': '',
      'option a': ' ',
      'option b': ' ',
      'option c': ' ',
      'option d': ' ',
      'answer': ' ',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question': 'The polar coordinates of ( 2,2√3) is ',
      'option a': ' none',
      'option b': 'both c and d ',
      'option c': '   ( 4,60 deg)  ',
      'option d': '   ( 2,30 deg) ',
      'answer': '   ( 4,60 deg) ',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question': 'The value of (𝑖 + 𝑖)20 is',
      'option a': ' 2 power 10',
      'option b': '2 power 15 ',
      'option c': ' 2 power 18 ',
      'option d': '2 power -10 ',
      'answer': ' 2 power -10',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question': 'Every continuous function is ',
      'option a': ' Increasing     ',
      'option b': '  decreasing ',
      'option c': '  not always differentiable ',
      'option d': ' always differentiable ',
      'answer': ' not always differentiable  ',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question':
          'The general equation of 2nd degree 𝑎x2 + 2ℎxy + 𝑏y2 + 2𝑔x + 2𝑓y + 𝑐 = 0 represents a circle if',
      'option a': ' 𝑎 + 𝑏 = 0  ',
      'option b': '𝑎 = 𝑏 = ℎ = 0  ',
      'option c': ' 𝑎 = 𝑏;𝑐𝑜𝑒𝑓𝑓 𝑜𝑓 xy = 0  ',
      'option d': ' none',
      'answer': 'none ',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question':
          'If w is the cube root of unit, then the value of   (1 – w + w2) 5 + (1 + w - w2) 5   = ',
      'option a': ' 16',
      'option b': '32 ',
      'option c': '48 ',
      'option d': '-16 ',
      'answer': ' 32',
      'solution': 'https://www.neptechpal.com ',
    },
  ],

  //8

  [
    {
      'question': 'Animals that can live on land and water. ',
      'option a': ' Amphibiou ',
      'option b': 'terresterial ',
      'option c': 'aquatic ',
      'option d': 'aquarium ',
      'answer': ' Amphibiou ',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question': 'Person who eats human flesh ',
      'option a': ' cannibal',
      'option b': 'furious ',
      'option c': ' carnivorous',
      'option d': ' beast',
      'answer': 'cannibal ',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question': 'A word which can be interpreted in more than one way ',
      'option a': 'stuπd ',
      'option b': ' confusing',
      'option c': 'foolish ',
      'option d': '  ambiguou',
      'answer': '  ambiguou',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question': 'A place where birds are kept',
      'option a': 'aviary ',
      'option b': 'zoo ',
      'option c': ' nursery',
      'option d': ' attic',
      'answer': 'aviary ',
      'solution': 'https://www.neptechpal.com ',
    },
//5
    {
      'question': 'A hater of learning and knowledge ',
      'option a': '  misologist',
      'option b': 'misogynist ',
      'option c': 'misogyniste ',
      'option d': ')misomthroπst ',
      'answer': '  misologist',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question': 'He arrived ………………. the airport ………….. time for the plane',
      'option a': ' in, in',
      'option b': 'at, on  ',
      'option c': 'on, in ',
      'option d': ' at, in',
      'answer': ' at, on ',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question':
          'You’re always ……….. a hurry. You drive ……………. a tremendous speed',
      'option a': ' for, at',
      'option b': ' at,on',
      'option c': ' on, with',
      'option d': ' in,at',
      'answer': ' for, at',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question':
          ' I am interested ………. cricket but I am not very good ….. it.',
      'option a': ' in, in ',
      'option b': 'in,with ',
      'option c': ' in,at',
      'option d': 'with, at ',
      'answer': ' with, at',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question': 'What plat-form does the train ……….. Zurich leaves ………..?',
      'option a': 'for, with ',
      'option b': '  for, in ',
      'option c': 'for, from ',
      'option d': ' in, from',
      'answer': '  for, in ',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question': 'To took a gift horse in the mouth ',
      'option a': ' to appreciate a gift or favor.',
      'option b': 'to accept something ungratefully  ',
      'option c': ' to acknowledge something greatly  ',
      'option d': ' to be indifferent',
      'answer': 'to accept something ungratefully  ',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question': 'To let the grass grow under one’s feet ',
      'option a': ' to miss the opportunity  ',
      'option b': '  to waste no time in doing something',
      'option c': ' to idle away the time; to delay and linger ',
      'option d': 'to let things go on in their natural way  ',
      'answer': 'to idle away the time; to delay and linger  ',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question': 'A snake in the grass',
      'option a': 'a treacherous or hidden enemy  ',
      'option b': ' not a reliable person ',
      'option c': ' unexpected happening',
      'option d': 'recognizable derringer  ',
      'answer': ' a treacherous or hidden enemy ',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question': 'To wash one’s dirty lines in public',
      'option a': ' to quarrel in the ope',
      'option b': '  to do some ugly work in the public ',
      'option c': ' to discuss private matters before strength',
      'option d': 'none ',
      'answer': 'to discuss private matters before strength ',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question': 'The residents celebrated the Independence day.',
      'option a': ' The Independence Day has been celebrated by the resident',
      'option b': 'The Independence Day was celebrated by the residents ',
      'option c': 'The Independence Day is celebrated by the residents. ',
      'option d': ' The Independence Day has been celebrated by the resident',
      'answer': ' The Independence Day was celebrated by the residents',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question': 'His pocket has been πcked',
      'option a': '  They have his pocket πcked  c',
      'option b': 'πcked has been his pocket ',
      'option c': ' ) Someone has πcked his pocket',
      'option d': ' πcking has been done to his pocket ',
      'answer': ' ) Someone has πcked his pocket',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question': 'I saw him leaving the hous',
      'option a': ' leaving the house he was seen by me. c',
      'option b': 'He was seen to be leaving the house by me ',
      'option c': 'He had been seen leaving the house by me ',
      'option d': ' he was seen leaving the house by me',
      'answer': ' he was seen leaving the house by me',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question': 'We hope that we shall win the match ',
      'option a': 'Winning the match is hoped by us ',
      'option b': 'It is hoped that the match will be won by us',
      'option c': 'The match is hoped to be won ',
      'option d': ' Match winning is our hope.',
      'answer': 'It is hoped that the match will be won by us ',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question': ' I am next in the queue….……….. ? ',
      'option a': 'Isn’t I ',
      'option b': 'Am not I ',
      'option c': 'aren’t I  ',
      'option d': '  am I',
      'answer': 'aren’t I  ',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question': 'You had better start using them more………? ',
      'option a': ' hadn’t    you',
      'option b': ' aren’t you  ',
      'option c': '  have you ',
      'option d': 'none ',
      'answer': 'hadn’t    you ',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question': 'Asian people don’t like rice ……… ?',
      'option a': ' aren’t they ',
      'option b': ' do they ',
      'option c': 'doesn’t ',
      'option d': ' Isn’t it   ',
      'answer': ' do they ',
      'solution': 'https://www.neptechpal.com ',
    },
  ],

  //9

  [
    {
      'question': 'The people from ______ I am descended were heartily seated',
      'option a': ' where',
      'option b': ' what',
      'option c': 'whose ',
      'option d': 'when ',
      'answer': ' when',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question': 'I want to have my glasses …………………. ',
      'option a': 'fit ',
      'option b': ' fitted',
      'option c': ' fit on',
      'option d': ' fitted on',
      'answer': ' fitted on',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question': 'There is……………… children’s center in our zoo',
      'option a': ' a',
      'option b': ' an',
      'option c': 'the ',
      'option d': 'nothing ',
      'answer': ' the',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question': 'He got married ………….20. ',
      'option a': ' on',
      'option b': ' in',
      'option c': 'the ',
      'option d': 'at ',
      'answer': 'at ',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question': ' She hardly drinks …………? ',
      'option a': ' does she ',
      'option b': 'is she ',
      'option c': ' none',
      'option d': "isn't she ",
      'answer': '  does she',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question': 'My sisters got a tailor…………………..a couple of shirts',
      'option a': ' made',
      'option b': 'to make  ',
      'option c': 'makes ',
      'option d': ' make',
      'answer': 'to make  ',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question': 'Economics ………..an important subject',
      'option a': ' have',
      'option b': 'are ',
      'option c': ' were',
      'option d': 'is ',
      'answer': 'is ',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question': 'Nobody loves and cares me, …………? ',
      'option a': 'doesnot they ',
      'option b': 'does he ',
      'option c': ' dont they',
      'option d': ' do they',
      'answer': 'do they ',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question': ' What the synonyms is of mitigate',
      'option a': 'beneficial ',
      'option b': ' fastidious',
      'option c': 'Increase ',
      'option d': ' Reliance',
      'answer': ' Reliance',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question': 'The lecturer and the poet…………….popular in this city',
      'option a': 'are ',
      'option b': ' in',
      'option c': 'were ',
      'option d': 'none ',
      'answer': 'are ',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question': 'Do you ……..me …………a fool? ',
      'option a': ' take, in',
      'option b': ' take, to',
      'option c': 'take, for  ',
      'option d': ' take, after ',
      'answer': ' take, to',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question': 'More than one hundred people …………….to the meeting  a',
      'option a': 'was coming ',
      'option b': ' has come',
      'option c': 'is coming ',
      'option d': 'have come ',
      'answer': 'is coming ',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question': 'The word ‘father’ takes the suffix',
      'option a': ' …. Is',
      'option b': '  ….ly',
      'option c': ' …… some',
      'option d': '……..y  ',
      'answer': ' ….ly ',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question': 'In the word ……………….the stress falls on the second syllable',
      'option a': 'Vegetarian ',
      'option b': 'Passenger ',
      'option c': ' geography  ',
      'option d': 'Photographic ',
      'answer': ' geography  ',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question':
          'The word ‘catch’ has the same final consonant sound as the word?',
      'option a': ' mouse',
      'option b': ' pack ',
      'option c': ' monarch',
      'option d': 'witch ',
      'answer': 'witch ',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question': 'This is the family…………….. anniversary we were celebrating ',
      'option a': 'whose ',
      'option b': ' that',
      'option c': ' who',
      'option d': 'whom ',
      'answer': ' whose',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question': 'Shall we go by bus or by train? ',
      'option a': ' falling',
      'option b': ' falling, rising',
      'option c': ' falling,falling',
      'option d': 'rising, falling  ',
      'answer': 'rising, falling  ',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question': 'This is the family…………….. anniversary we were celebrating ',
      'option a': 'whose ',
      'option b': ' that',
      'option c': ' who',
      'option d': 'whom ',
      'answer': ' whose',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question': 'Which one is a singular? ',
      'option a': '  medium',
      'option b': ' media',
      'option c': 'mediis ',
      'option d': ' medias',
      'answer': '  medium',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question': ' I am getting him  …………….. my bed',
      'option a': ' to make  ',
      'option b': 'makes  ',
      'option c': 'made ',
      'option d': 'make ',
      'answer': ' to make  ',
      'solution': 'https://www.neptechpal.com ',
    },
  ],

  //10

  [
    {
      'question': 'Animals that can live on land and water. ',
      'option a': ' Amphibiou ',
      'option b': 'terresterial ',
      'option c': 'aquatic ',
      'option d': 'aquarium ',
      'answer': ' Amphibiou ',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question': 'Person who eats human flesh ',
      'option a': ' cannibal',
      'option b': 'furious ',
      'option c': ' carnivorous',
      'option d': ' beast',
      'answer': 'cannibal ',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question': 'A word which can be interpreted in more than one way ',
      'option a': 'stuπd ',
      'option b': ' confusing',
      'option c': 'foolish ',
      'option d': '  ambiguou',
      'answer': '  ambiguou',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question': 'A place where birds are kept',
      'option a': 'aviary ',
      'option b': 'zoo ',
      'option c': ' nursery',
      'option d': ' attic',
      'answer': 'aviary ',
      'solution': 'https://www.neptechpal.com ',
    },
//5
    {
      'question': 'A hater of learning and knowledge ',
      'option a': '  misologist',
      'option b': 'misogynist ',
      'option c': 'misogyniste ',
      'option d': ')misomthroπst ',
      'answer': '  misologist',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question': 'He arrived ………………. the airport ………….. time for the plane',
      'option a': ' in, in',
      'option b': 'at, on  ',
      'option c': 'on, in ',
      'option d': ' at, in',
      'answer': ' at, on ',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question':
          'You’re always ……….. a hurry. You drive ……………. a tremendous speed',
      'option a': ' for, at',
      'option b': ' at,on',
      'option c': ' on, with',
      'option d': ' in,at',
      'answer': ' for, at',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question':
          ' I am interested ………. cricket but I am not very good ….. it.',
      'option a': ' in, in ',
      'option b': 'in,with ',
      'option c': ' in,at',
      'option d': 'with, at ',
      'answer': ' with, at',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question': 'What plat-form does the train ……….. Zurich leaves ………..?',
      'option a': 'for, with ',
      'option b': '  for, in ',
      'option c': 'for, from ',
      'option d': ' in, from',
      'answer': '  for, in ',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question': 'To took a gift horse in the mouth ',
      'option a': ' to appreciate a gift or favor.',
      'option b': 'to accept something ungratefully  ',
      'option c': ' to acknowledge something greatly  ',
      'option d': ' to be indifferent',
      'answer': 'to accept something ungratefully  ',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question': 'To let the grass grow under one’s feet ',
      'option a': ' to miss the opportunity  ',
      'option b': '  to waste no time in doing something',
      'option c': ' to idle away the time; to delay and linger ',
      'option d': 'to let things go on in their natural way  ',
      'answer': 'to idle away the time; to delay and linger  ',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question': 'A snake in the grass',
      'option a': 'a treacherous or hidden enemy  ',
      'option b': ' not a reliable person ',
      'option c': ' unexpected happening',
      'option d': 'recognizable derringer  ',
      'answer': ' a treacherous or hidden enemy ',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question': 'To wash one’s dirty lines in public',
      'option a': ' to quarrel in the ope',
      'option b': '  to do some ugly work in the public ',
      'option c': ' to discuss private matters before strength',
      'option d': 'none ',
      'answer': 'to discuss private matters before strength ',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question': 'The residents celebrated the Independence day.',
      'option a': ' The Independence Day has been celebrated by the resident',
      'option b': 'The Independence Day was celebrated by the residents ',
      'option c': 'The Independence Day is celebrated by the residents. ',
      'option d': ' The Independence Day has been celebrated by the resident',
      'answer': ' The Independence Day was celebrated by the residents',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question': 'His pocket has been πcked',
      'option a': '  They have his pocket πcked  c',
      'option b': 'πcked has been his pocket ',
      'option c': ' ) Someone has πcked his pocket',
      'option d': ' πcking has been done to his pocket ',
      'answer': ' ) Someone has πcked his pocket',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question': 'I saw him leaving the hous',
      'option a': ' leaving the house he was seen by me. c',
      'option b': 'He was seen to be leaving the house by me ',
      'option c': 'He had been seen leaving the house by me ',
      'option d': ' he was seen leaving the house by me',
      'answer': ' he was seen leaving the house by me',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question': 'We hope that we shall win the match ',
      'option a': 'Winning the match is hoped by us ',
      'option b': 'It is hoped that the match will be won by us',
      'option c': 'The match is hoped to be won ',
      'option d': ' Match winning is our hope.',
      'answer': 'It is hoped that the match will be won by us ',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question': ' I am next in the queue….……….. ? ',
      'option a': 'Isn’t I ',
      'option b': 'Am not I ',
      'option c': 'aren’t I  ',
      'option d': '  am I',
      'answer': 'aren’t I  ',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question': 'You had better start using them more………? ',
      'option a': ' hadn’t    you',
      'option b': ' aren’t you  ',
      'option c': '  have you ',
      'option d': 'none ',
      'answer': 'hadn’t    you ',
      'solution': 'https://www.neptechpal.com ',
    },
    {
      'question': 'Asian people don’t like rice ……… ?',
      'option a': ' aren’t they ',
      'option b': ' do they ',
      'option c': 'doesn’t ',
      'option d': ' Isn’t it   ',
      'answer': ' do they ',
      'solution': 'https://www.neptechpal.com ',
    },
  ],
];
