const List teammembers = [
  {
    'name': 'Bibek Acharya',
    'position': 'Developer',
    'image': 'images/bibek.jpg',
    'fblink': 'https://www.facebook.com/bibekacharya956',
    'twilink': 'https://twitter.com/neptechpal',
    'instlink': 'https://www.instagram.com/bibekacharya955'
  },
  {
    'name': 'Nabin Lamsal',
    'position': 'Content Editor',
    'image': 'images/nabin.jpg',
    'fblink': 'https://www.facebook.com/lamsal.navin',
    'twilink': 'https://twitter.com/neptechpal',
    'instlink': 'https://www.instagram.com/',
  },
  {
    'name': 'Magnus Pokhrel',
    'position': 'Advisor',
    'image': 'images/male1.png',
    'fblink': 'https://www.facebook.com/bibekacharya955',
    'twilink': 'https://twitter.com/neptechpal',
    'instlink': 'https://www.instagram.com/',
  },
  {
    'name': 'Sangam Giri',
    'position': 'Content Editor',
    'image': 'images/sangamgiri1.jpg',
    'fblink': 'https://www.facebook.com/sangam.giri.58555',
    'twilink': 'https://twitter.com/neptechpal',
    'instlink': 'https://www.instagram.com/sangam_official0.0/',
  },
  {
    'name': 'Anil  Shrestha',
    'position': 'Advisor',
    'image': 'images/anil.jpg',
    'fblink': 'https://www.facebook.com/sthaanil66',
    'twilink': 'https://twitter.com/neptechpal',
    'instlink': 'https://www.instagram.com/sthaanil66/',
  },
  {
    'name': 'Sangam Poudel',
    'position': 'Content Editor',
    'image': 'images/sangampdl.jpg',
    'fblink': 'https://www.facebook.com/sangam.paudel.7583',
    'twilink': 'https://twitter.com/neptechpal',
    'instlink': 'https://www.instagram.com/its.sangam/',
  },
  {
    'name': 'Nischal Basnet',
    'position': 'Graphics Designer',
    'image': 'images/nischal.png',
    'fblink': 'https://www.facebook.com/bbsnet.nischal',
    'twilink': 'https://twitter.com/neptechpal',
    'instlink': 'https://www.instagram.com/chuklukeditor/',
  },
  // {
  //   'name': 'Person name',
  //   'position': 'Position',
  //   'image': 'images/female.png',
  //   'fblink': 'https://www.facebook.com/bibekacharya955',
  //   'twilink': 'https://www.twitter.com/',
  //   'instlink': 'https://www.instagram.com/',
  // },
];
